export enum ActionType {
  LOADING = "LOADING",
  LOADED = "LOADED",
  USER_LOADED = "USER_LOADED",
  AUTH_ERROR = "AUTH_ERROR",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAIL = "REGISTER_FAIL",
  GET_ERRORS = "GET_ERRORS",
  CLEAR_ERRORS = "CLEAR_ERRORS",

  COURSE_LOAD = "COURSE_LOAD",
  COURSE_ADD = "COURSE_ADD",
  COURSE_REMOVE = "COURSE_REMOVE",
  COURSE_LOADING = "COURSE_LOADING",
  COURSE_SELECT = "COURSE_SELECT",
}
