# Generated by Django 3.2.5 on 2021-07-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isTeacher',
            new_name='is_teacher',
        ),
    ]
